[project]
name = "demo"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "bcrypt>=4.3.0",
    "django-qrcode>=0.3",
    "qrcode[pil]>=8.2",
]
