# printing the integer values of a character

A = ord('A')
B = ord('B')
C = ord('C')
D = ord('D')
b = ord('b')
c = ord('c')
d = ord('d')
e = ord('0')
f = ord('1')
g = ord('2')
h = ord('$')
i = ord('*')
j = ord('+')
k = ord(' ')

print("The character value of A is: ", A)
print("The character value of B is: ", B)
print("The character value of C is: ", C)
print("The character value of D is: ", D)
print("The character value of b is: ", b)
print("The character value of c is: ", c)
print("The character value of d is: ", d)
print("The character value of 0 is: ", e)
print("The character value of 1 is: ", f)
print("The character value of 2 is: ", g)
print("The character value of $ is: ", h)
print("The character value of * is: ", i)
print("The character value of + is: ", j)
print("The character value of ' ' is: ", k)