# integer value of a character

a = ord('A')
b = ord('B')
c = ord('C')
d = ord('D')
e = ord('b')
f = ord('c')
g = ord('d')
h = ord('0')
i = ord('1')
j = ord('2')
k = ord('$')
l = ord('*')
m = ord('+')
n = ord(' ')

print('The value of A is ', a)
print('The value of B is ', b)
print('The value of C is ', c)
print('The value of D is ', d)
print('The value of b is ', e)
print('The value of c is ', f)
print('The value of d is ', g)
print('The value of 0 is ', h)
print('The value of 1 is ', i)
print('The value of 2 is ', j)
print('The value of $ is ', k)
print('The value of * is ', l)
print('The value of + is ', m)
print('The value of ' ' is ', n)